//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLoggingCompanyProject {
    
    
    public partial class Game {
        
        /// <summary>
        /// navHtml control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheLoggingCompanyProject.architecture.Nav navHtml;
        
        /// <summary>
        /// footerHtml control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheLoggingCompanyProject.architecture.Footer footerHtml;
    }
}
